### ISSUE TITLE
No import option?

### ISSUE THREAD

**Issue by GameSlayar** [freundTech/blender2minecraft#6]
It seems that wth the latest version of *Blender* and *Blender2Minecraft* I cannot import a **.json** file.

**Comment by GameSlayar** [comment]
*Export*, however, seems to work fine

**Comment by freundTech** [comment]
I haven't worked on this addon in a long time. Work on an import feature was never started.
I think @lipki worked on an import feature some time ago, but I don't know if it was finished.

If I ever pick up this project again this will be one of the first features I'll add though.
Don't have a lot of time at the moment.

**Comment by lipki** [comment]
I worked on the import, but as I was not familiar with the original code, I have not really succeeded.
Also I found another tool that works very well: D
Model Creator
